# Generated by Django 6.0.7 on 2026-08-01 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Concurso')),
                ('banca', models.CharField(blank=True, max_length=100, verbose_name='Banca')),
                ('data_prova', models.DateField(blank=True, null=True, verbose_name='Data da Prova')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['data_prova'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('peso', models.IntegerField(default=1, help_text='Importância da matéria (1-10)', verbose_name='Peso')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('revisado', 'Revisado'), ('dominado', 'Dominado')], default='nao_iniciado', max_length=20, verbose_name='Status')),
                ('concurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.concurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10, verbose_name='Período')),
                ('horas_objetivo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Horas Objetivo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Estudo',
                'verbose_name_plural': 'Metas de Estudo',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('status', models.CharField(choices=[('nao_estudado', 'Não Estudado'), ('em_andamento', 'Em Andamento'), ('revisado', 'Revisado'), ('dominado', 'Dominado')], default='nao_estudado', max_length=20, verbose_name='Status')),
                ('ultima_revisao', models.DateField(blank=True, null=True, verbose_name='Última Revisão')),
                ('proxima_revisao', models.DateField(blank=True, null=True, verbose_name='Próxima Revisão')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='core.materia')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('duracao_minutos', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('tipo', models.CharField(choices=[('teoria', 'Teoria'), ('exercicios', 'Exercícios'), ('revisao', 'Revisão'), ('simulado', 'Simulado')], default='teoria', max_length=20, verbose_name='Tipo')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Anotações')),
                ('produtividade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2, verbose_name='Produtividade')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topico')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-data'],
            },
        ),
    ]
