# Generated by Django 6.0.7 on 2026-08-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('status', models.CharField(choices=[('nao_estudado', 'Não Estudado'), ('em_andamento', 'Em Andamento'), ('revisado', 'Revisado'), ('dominado', 'Dominado')], default='nao_estudado', max_length=20, verbose_name='Status')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='core.topico')),
            ],
            options={
                'verbose_name': 'Subtópico',
                'verbose_name_plural': 'Subtópicos',
                'ordering': ['nome'],
            },
        ),
    ]
